config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :categories, only: [:index, :show, :new, :create]
  resources :products, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories,  dependent: :destroy
  has_many :categories, through: :product_categories

  validates :title, presence: true
  validates :description, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

  def new
    @category = Category.new
    @products = Product.order(created_at: :desc).limit(10)
  end

  def create
    @category = Category.new(category_params)
    product_params[:products_10_most_recently_created].each do |product|
      if product.length > 0
        @product = Product.find(product.to_i)
        @category.products << @product
      end
    end
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  private

  def product_params
    params[:category].require(:product_categories).permit({products_10_most_recently_created:[]})
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @categories = @product.categories
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    category_params[:categories].each do |category|
      if category.length > 0
        @category = Category.find(category.to_i)
        @product.categories << @category
      end
    end
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  private
  def category_params
    params[:product].require(:product_categories).permit({categories:[]})
  end

  def product_params
    params.require(:product).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>Categories index page</h1>
<ul>
  <% @categories.each do |category| %>
  <li>
    <%= link_to category.name, category_path(category) %>
  </li>
  <% end %>
</ul>

<%= link_to "Back to home page", root_path %>
<br>
<%= link_to "Create a new category", new_category_path %>

app/views/categories/new.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.simple_fields_for :product_categories do |t|%>
    <%= t.input :products_10_most_recently_created, collection: @products, as: :check_boxes %>
  <% end %>
<%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/categories/show.html.erb
<h1>Category show page</h1>
<%= @category.name %>
<h2>products in this category</h2>
<ul>
  <% @products.each do |product| %>
  <li>
    <%= link_to product.title, product_path(product) %>
    <%= product.description %>
    <%= product.created_at %>
  </li>
  <% end %>
</ul>

<%= link_to "Back to categories page", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Product and Categories</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home page</h1>

<%= link_to "View all the categories", categories_path %>
<br>
<%= link_to "View all products", products_path %>
<br>
<%= link_to "Create a new category", new_category_path %>
<br>
<%= link_to "Create a new product", new_product_path %>

app/views/products/index.html.erb
<h1>Product index page</h1>
<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.title, product_path(product) %>
      <%= product.created_at %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to home page", root_path %>
<br>
<%= link_to "Create a new product", new_product_path %>

app/views/products/new.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.simple_fields_for :product_categories do |t|%>
    <%= t.input :categories, collection: @categories, as: :check_boxes %>
  <% end %>
<%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/products/show.html.erb
<h1>Product show page</h1>

<%= @product.title %>
<br>
<%= @product.description %>
<br>
<%= @product.created_at %>
<br>
<h2>Product categories</h2>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to product index page", products_path %>
<br>
<%= link_to "Create a new product", new_product_path %>